import { Dimensions, StyleSheet } from "react-native";

const sidebarStyles = StyleSheet.create({
    fullScreen: {
        flex: 1,
    },
    contentContainer: {
        flex: 1,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    sidebar: {
        flex: 1,
        backgroundColor: "#f0f2faff",
        paddingTop: 50,
    },
    closeButton: {
        position: 'absolute',
        top: 40,
        left: 20,
        zIndex: 10,
        padding: 6,
        borderRadius: 20,
    },
    profileSection: {
        alignItems: "center",
        marginBottom: 30,
        paddingHorizontal: 10,
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 10,
        backgroundColor: "#eee",
        borderWidth: 2,
        borderColor: '#ccc',
    },
    name: {
        fontSize: 18,
        fontFamily: 'Poppins_500Medium',
        color: "#707070",
        textAlign: 'center',
    },
    email: {
        fontSize: 14,
        fontFamily: 'Poppins_400Regular',
        color: "#BEBEBE",
        textAlign: 'center',
    },
    menuItemsContainer: {
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    menuItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: 'flex-start',
        width: '100%',
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderRadius: 25,
        backgroundColor: '#FFFFFF',
        borderWidth: 0,
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    menuText: {
        marginLeft: 18,
        fontSize: 16,
        fontFamily: 'Poppins_400Regular',
        color: "#737373",
        flex: 1,
    },
    logoutItem: {
        backgroundColor: '#FFFFFF',
        borderWidth: 0,
    },
    logoutText: {
        color: "red",
        marginLeft: 18,
        fontSize: 16,
        fontFamily: 'Poppins_400Regular',
        flex: 1,
    },
    logoContainer: {
        alignItems: "center",
        marginBottom: 10,
    },
    logo: {
        width: 250,
        height: 150,
        resizeMode: 'contain',
    },
    version: {
        fontSize: 12,
        fontFamily: 'Poppins_400Regular',
        color: "#bbb",
        display: 'none',
    },
    menuButton: {
        position: "absolute",
        top: 40,
        left: 20,
        zIndex: 10,
        backgroundColor: "#fff",
        borderRadius: 20,
        padding: 6,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    sidebarOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        width: Dimensions.get("window").width * 0.70,
        height: "100%",
        backgroundColor: "#F0F8FF",
        zIndex: 9999,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 4, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    blurOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 9998,
        backgroundColor: 'rgba(0,0,0,0.3)',
    },
    scrollViewContent: {
        flexGrow: 1,
        paddingTop: 20,
        paddingBottom: 50,
    }
});

export default sidebarStyles;