import { Dimensions, StyleSheet } from 'react-native';
import { FONTS } from '../../constants/fonts';

const { width } = Dimensions.get('window');

export const loginScreenStyles = StyleSheet.create({
    screenContainer: {
        flex: 1,
        backgroundColor: "#fff",
        paddingTop: 0,
    },
    keyboardAvoidingView: {
        flex: 1,
    },
    scrollViewContent: {
        flexGrow: 1,
        alignItems: 'center',
        paddingTop: 60,
        paddingBottom: 20,
        backgroundColor: "#fff",
    },
    logo: {
        width: width * 1,
        height: width * 0.4,
        marginTop: 50,
    },
    pressableContainer: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
    },

    form: {
        width: "90%",
        paddingHorizontal: 20,
        alignItems: 'center',
        marginBottom: 40,
        backgroundColor: "#fff",
    },
    welcomeText: {
        fontSize: 22,
        fontFamily: FONTS.regular,
        color: "#65B65F",
        marginBottom: 5,
        marginTop: 5,
        flexDirection: 'row',
        alignItems: 'center',
    },
    signInPrompt: {
        fontSize: 22,
        fontFamily: FONTS.regular,
        color: "#363636",
        marginBottom: 20,
        textAlign: 'center',
    },
    offerText: {
        fontSize: 14,
        color: "#666",
        textAlign: "center",
        marginBottom: 30,
        fontFamily: FONTS.regular,
    },
    tabContainer: {
        flexDirection: "row",
        backgroundColor: "#F0F0F0",
        borderRadius: 100,
        marginBottom: 20,
    },
    activeTab: {
        flex: 1,
        paddingVertical: 12,
        backgroundColor: "#fff",
        borderRadius: 100,
        alignItems: "center",
        margin: 5,
    },
    activeTabText: {
        color: "#65B65F",
        fontFamily: FONTS.bold,
    },
    inactiveTab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: "center",
    },
    inactiveTabText: {
        color: "#999",
        margin: 5,
        fontFamily: FONTS.regular,
    },
    label: {
        alignSelf: "flex-start",
        fontSize: 16,
        color: "#555",
        marginBottom: 8,
        marginTop: 0,
        fontFamily: FONTS.regular,
    },
    input: {
        width: "100%",
        height: 50,
        backgroundColor: "#E8F5E9",
        borderRadius: 100,
        paddingHorizontal: 15,
        fontSize: 16,
        color: "#363636",
        borderWidth: 1,
        borderColor: "#E0E0E0",
        marginBottom: 10,
        fontFamily: FONTS.regular,
    },
    passwordInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "100%",
        height: 50,
        backgroundColor: "#E8F5E9",
        borderRadius: 100,
        paddingHorizontal: 15,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        marginBottom: 20,
    },
    passwordInput: {
        flex: 1,
        fontSize: 16,
        color: "#363636",
        fontFamily: FONTS.regular,
    },
    eyeIcon: {
        paddingLeft: 10,
    },
    loginButton: {
        width: "100%",
        height: 55,
        backgroundColor: "#65B65F",
        borderRadius: 100,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 20,
    },
    loginButtonText: {
        color: "#fff",
        fontSize: 18,
        fontFamily: FONTS.bold,
    },
    rememberMeContainer: {
        flexDirection: "row",
        alignItems: "center",
        alignSelf: "flex-start",
        marginBottom: 40,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: "#ccc",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 10,
    },
    checkedCheckbox: {
        width: 12,
        height: 12,
        borderRadius: 3,
        backgroundColor: "#65B65F",
    },
    rememberMeText: {
        fontSize: 14,
        color: "#555",
        fontFamily: FONTS.regular,
    },
    registerLink: {
        fontSize: 14,
        color: "#888",
        marginTop: 20,
        fontFamily: FONTS.regular,
    },
});