import { StyleSheet } from 'react-native';
import { FONTS } from '../../constants/fonts';

const styles = StyleSheet.create({
  fullContainer: {
    flex: 1,
    backgroundColor: '#F6F9FF',
  },
  contentScroll: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingBottom: 20,
    alignItems: 'stretch',
    paddingHorizontal: 20,
  },
  innerWrap: {
    width: '100%',
    flexGrow: 1,
    justifyContent: 'flex-start',
  },
  paymentCard: {
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    padding: 20,
    width: '100%',
    marginBottom: 40,
  },
  cardHeader: {
    backgroundColor: '#e6fcdcff',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    paddingVertical: 25,
    paddingHorizontal: 20,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '100%',
  },
  cardTitle: {
    fontSize: 20,
    fontFamily: FONTS.bold,
    color: '#000',
  },
  saleIdText: {
    fontSize: 14,
    color: '#545454',
    marginTop: 5,
    fontFamily: FONTS.regular,
  },
  formSection: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    color: '#404040',
    fontFamily: FONTS.semiBold,
    marginBottom: 10,
  },
  input: {
    backgroundColor: '#F6F9FF',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: '#363636',
    minHeight: 50,
    fontFamily: FONTS.regular,
  },
  editableInput: {
    borderRadius: 33,
  },
  disabledInput: {
    backgroundColor: '#EAEFFF',
    color: '#A0A0A0',
    borderRadius: 33,
  },
  infoPaymentText: {
    fontSize: 12,
    color: '#999',
    marginTop: 5,
    marginLeft: 15,
    fontFamily: FONTS.regular,
  },
  radioGroupVertical: {
    flexDirection: 'column',
    marginTop: 5,
  },
  radioOptionVertical: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 25,
    width: '100%',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  radioButton: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  radioSelected: {
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: '#65B65F',
  },
  radioLabel: {
    fontSize: 16,
    color: '#363636',
    fontFamily: FONTS.regular,
  },
  payButton: {
    backgroundColor: '#65B65F',
    borderRadius: 25,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  disabledPayButton: {
    backgroundColor: '#A0A0A0',
  },
  payButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: FONTS.bold,
  },
  loadingMethodsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  loadingMethodsText: {
    marginLeft: 10,
    color: '#65B65F',
    fontFamily: FONTS.regular,
  },
  errorMethodsContainer: {
    paddingVertical: 20,
  },
  errorMethodsText: {
    textAlign: 'center',
    color: 'red',
    fontFamily: FONTS.regular,
  },
  documentInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  documentTypeDropdownInput: {
    backgroundColor: '#F6F9FF',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    minHeight: 50,
    width: 90,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  documentNumberInput: {
    flex: 1,
    backgroundColor: '#F6F9FF',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    minHeight: 50,
    marginLeft: 10,
    fontSize: 16,
    color: '#363636',
    fontFamily: FONTS.regular,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: FONTS.bold,
    marginBottom: 15,
    color: '#000',
  },
  documentTypeOption: {
    paddingVertical: 15,
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
  },
  documentTypeOptionText: {
    fontSize: 16,
    color: '#363636',
    fontFamily: FONTS.regular,
  },
  documentTypeFlatList: {
    maxHeight: 300,
  },
  closeButton: {
    borderRadius: 10,
    paddingVertical: 12,
    marginTop: 20,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: FONTS.bold,
  },
  copyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  copyText: {
    color: '#363636',
    flex: 1,
    marginRight: 8,
    fontFamily: FONTS.regular,
  },
  copyIconButton: {
    padding: 6,
  },
  copyAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  copyAllText: {
    color: '#65B65F',
    fontFamily: FONTS.semiBold,
  },
});

export default styles;
