import { Platform, StyleSheet } from 'react-native';
import { FONTS } from '../../constants/fonts';

export const registerScreenStyles = StyleSheet.create({
    screenContainer: {
        flexGrow: 1,
        alignItems: "center",
        backgroundColor: "#fff",
        paddingTop: 0,
        paddingBottom: 50,
    },
    pressableContainer: {
        flexGrow: 1,
        alignItems: 'center',
        width: '100%',
    },
    disabledInput: {
        backgroundColor: '#f0f0f0',
        color: '#999',
    },
    disabledBorder: {
        borderColor: '#ccc',
    },
    checkButton: {
        backgroundColor: '#65B65F',
        padding: 8,
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
    },
    resetButton: {
        backgroundColor: 'red',
    },
    form: {
        width: "90%",
        paddingHorizontal: 20,
        alignItems: 'center',
        marginTop: 40,
        paddingTop: 60,
        paddingBottom: Platform.OS === 'ios' ? 0 : 30,
    },
    welcomeText: {
        fontSize: 22,
        fontFamily: FONTS.regular,
        color: "#65B65F",
        marginBottom: 5,
        marginTop: 40,
        flexDirection: 'row',
        alignItems: 'center',
    },
    signInPrompt: {
        fontSize: 22,
        fontFamily: FONTS.regular,
        color: "#363636",
        marginBottom: 5,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 16,
        color: "#666",
        textAlign: "center",
        marginBottom: 2,
        fontFamily: FONTS.regular,
    },
    tabContainer: {
        flexDirection: "row",
        backgroundColor: "#F0F0F0",
        borderRadius: 100,
        marginBottom: 30,
        marginTop: 20,
    },
    activeTab: {
        flex: 1,
        paddingVertical: 12,
        backgroundColor: "#fff",
        borderRadius: 100,
        alignItems: "center",
        margin: 5,
    },
    activeTabText: {
        color: "#65B65F",
        fontFamily: FONTS.bold,
    },
    inactiveTab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: "center",
    },
    inactiveTabText: {
        color: "#999",
        margin: 5,
        fontFamily: FONTS.regular,
    },
    label: {
        alignSelf: "flex-start",
        fontSize: 16,
        color: "#555",
        marginBottom: 8,
        marginTop: 15,
        fontFamily: FONTS.regular,
    },
    input: {
        width: "100%",
        height: 50,
        backgroundColor: "#E8F5E9",
        borderRadius: 100,
        paddingHorizontal: 15,
        fontSize: 16,
        color: "#363636",
        borderWidth: 1,
        borderColor: "#E0E0E0",
        marginBottom: 10,
        justifyContent: 'center',
        fontFamily: FONTS.regular,
    },
    phoneInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "100%",
        height: 50,
        backgroundColor: "#E8F5E9",
        borderRadius: 100,
        paddingHorizontal: 15,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        marginBottom: 10,
    },
    countryPickerButton: {
        paddingRight: 15,
        height: '100%',
        justifyContent: 'center',
        borderRightWidth: 1,
        borderRightColor: "#E0E0E0",
    },
    countryCodeText: {
        fontSize: 16,
        color: "#363636",
        paddingHorizontal: 5,
        fontFamily: FONTS.regular,
    },
    phoneTextInput: {
        flex: 1,
        fontSize: 16,
        color: "#363636",
        paddingLeft: 10,
        paddingRight: 15,
        fontFamily: FONTS.regular,
    },
    passwordInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "100%",
        height: 50,
        backgroundColor: "#E8F5E9",
        borderRadius: 100,
        paddingHorizontal: 15,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        marginBottom: 20,
    },
    passwordInput: {
        flex: 1,
        fontSize: 16,
        color: "#363636",
        fontFamily: FONTS.regular,
    },
    eyeIcon: {
        paddingLeft: 10,
    },
    registerButton: {
        width: "100%",
        height: 55,
        backgroundColor: "#65B65F",
        borderRadius: 100,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 20,
    },
    registerButtonText: {
        color: "#fff",
        fontSize: 18,
        fontFamily: FONTS.bold,
    },
    termsContainer: {
        flexDirection: "row",
        alignItems: "center",
        alignSelf: "flex-start",
        marginBottom: 30,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 100,
        borderWidth: 2,
        borderColor: "#ccc",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 10,
    },
    checkedCheckbox: {
        width: 12,
        height: 12,
        borderRadius: 100,
        backgroundColor: "#65B65F",
    },
    termsText: {
        fontSize: 14,
        color: "#555",
        fontFamily: FONTS.regular,
    },
    boldText: {
        fontFamily: FONTS.bold,
    },
    registerLink: {
        fontSize: 14,
        color: "#888",
        marginTop: 16,
        marginBottom: 36,
        fontFamily: FONTS.regular,
    },
    datePickerModalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    datePickerModalContent: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 15,
        width: '85%',
        alignItems: 'center',
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.25,
                shadowRadius: 3.84,
            },
            android: {
                elevation: 5,
            },
        }),
    },
    datePickerModalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginTop: 20,
    },
    datePickerButton: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 50,
        backgroundColor: '#65B65F',
    },
    datePickerButtonText: {
        color: '#fff',
        fontFamily: FONTS.bold,
        fontSize: 16,
    },
    documentInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "100%",
        height: 50,
        backgroundColor: "#E8F5E9",
        borderRadius: 100,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        marginBottom: 10,
        zIndex: 1000,
    },
    documentTypeDropdownInput: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: 50,
        height: '100%',
        paddingLeft: 15,
        borderTopLeftRadius: 100,
        borderBottomLeftRadius: 100,
    },
    documentNumberInput: {
        flex: 1,
        height: '100%',
        paddingLeft: 10,
        paddingRight: 15,
        fontSize: 16,
        color: "#363636",
        borderLeftWidth: 1,
        borderColor: "#E0E0E0",
        borderTopRightRadius: 100,
        borderBottomRightRadius: 100,
        fontFamily: FONTS.regular,
    },
    modalTitle: {
        fontSize: 20,
        fontFamily: FONTS.bold,
        marginBottom: 15,
        color: '#363636',
    },
    documentTypeFlatList: {
        width: '100%',
        maxHeight: 200,
    },
    documentTypeOption: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        width: '100%',
        alignItems: 'center',
    },
    documentTypeOptionText: {
        fontSize: 16,
        color: '#363636',
        fontFamily: FONTS.regular,
    },
});